# description de ressources en lot
# à télécharger pour inclure dans descriptions
# exemple : exhibits that are not elements (so they have, for instance, an artistic value)

PREFIX display: <https://ouvroir.umontreal.ca/onto/display#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX ex: <http://example.org/>

CONSTRUCT {

  ?exhibit a crm:E22_Human-Made_Object ;
    crm:P2_has_type ex:some_term_in_vocabulary_call_it_AAT . # exemple
  	# etc.
}

WHERE {

  ?exhibit a display:Exhibit
  MINUS
  { ?exhibit a display:Element }

}